/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class update_employee */

#ifndef _Included_update_employee
#define _Included_update_employee
#ifdef __cplusplus
extern "C" {
#endif
#undef update_employee_serialVersionUID
#define update_employee_serialVersionUID 1i64
#undef update_employee_serialVersionUID
#define update_employee_serialVersionUID 1i64
/*
 * Class:     update_employee
 * Method:    update_emp
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_update_1employee_update_1emp
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
