/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class add_employee */

#ifndef _Included_add_employee
#define _Included_add_employee
#ifdef __cplusplus
extern "C" {
#endif
#undef add_employee_serialVersionUID
#define add_employee_serialVersionUID 1i64
#undef add_employee_serialVersionUID
#define add_employee_serialVersionUID 1i64
/*
 * Class:     add_employee
 * Method:    add_emp
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_add_1employee_add_1emp
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
