/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnid */

#ifndef _Included_jnid
#define _Included_jnid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnid
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnid_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
