/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class view_employee */

#ifndef _Included_view_employee
#define _Included_view_employee
#ifdef __cplusplus
extern "C" {
#endif
#undef view_employee_serialVersionUID
#define view_employee_serialVersionUID 1i64
#undef view_employee_serialVersionUID
#define view_employee_serialVersionUID 1i64
/*
 * Class:     view_employee
 * Method:    view_emp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_view_1employee_view_1emp
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
