/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class delete_employee */

#ifndef _Included_delete_employee
#define _Included_delete_employee
#ifdef __cplusplus
extern "C" {
#endif
#undef delete_employee_serialVersionUID
#define delete_employee_serialVersionUID 1i64
#undef delete_employee_serialVersionUID
#define delete_employee_serialVersionUID 1i64
/*
 * Class:     delete_employee
 * Method:    delete_emp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_delete_1employee_delete_1emp
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
